-- =============================================================================
-- TEST DATA ONLY (ADR 0015). Generated by scripts/generate-seed.mjs; do not edit.
-- Sources: supabase/seed/prototype-seed-data.json (prototype, unverified) and
-- supabase/seed/slice-content.json (fictional steps, documents and links).
-- Costs, deadlines and contacts are invented or unverified. Every category,
-- institution, life event and procedure title starts with "[TEST]".
-- Loaded locally, in CI and on staging; never in production.
-- =============================================================================

INSERT INTO categories (id, name, slug, icon, sort_order) VALUES
  ('10000000-0000-4000-8000-000000000001', '[TEST] Lična dokumenta', 'licna-dokumenta', 'id-card', 1),
  ('10000000-0000-4000-8000-000000000002', '[TEST] Preseljenje i adresa', 'preseljenje-i-adresa', 'house', 2);

INSERT INTO institutions (id, name, slug, kind, description, website, phone, email, working_hours, status) VALUES
  ('20000000-0000-4000-8000-000000000001', '[TEST] Ministarstvo unutrašnjih poslova (MUP)', 'mup', 'government', 'Nadležna institucija za lična dokumenta, registraciju vozila i prijavu prebivališta', 'https://mup.gov.rs', '+381 11 3618 700', 'kontakt@mup.gov.rs', '08:00-15:30, od ponedjeljka do petka', 'published');

INSERT INTO procedures (id, title, description, slug, can_online, can_in_person, can_by_mail, cost_type, cost_amount, cost_description, processing_time, official_link, form_link, last_verified_at) VALUES
  ('40000000-0000-4000-8000-000000000001', '[TEST] Prijava prebivališta', 'Prijavljuješ novu adresu stanovanja u MUP-u. Ovo je prvi korak nakon preseljenja.', 'prijava-prebivalista', false, true, false, 'free', NULL, NULL, '1 dan', 'https://mup.gov.rs', NULL, '2026-06-15T00:00:00Z'),
  ('40000000-0000-4000-8000-000000000002', '[TEST] Nova lična karta', 'Obnavljanje nove lične karte sa novom adresom', 'nova-licna-karta', false, true, false, 'fixed', '1500.00', 'Naknada za izradu', '3-5 radnih dana', 'https://mup.gov.rs', NULL, '2026-06-15T00:00:00Z'),
  ('40000000-0000-4000-8000-000000000003', '[TEST] Obnovljenje lične karte', 'Obnavljanje istekle lične karte', 'obnova-licne-karte', false, true, false, 'fixed', '1500.00', 'Naknada za izradu', '3-5 radnih dana', 'https://mup.gov.rs', NULL, '2026-06-15T00:00:00Z'),
  ('40000000-0000-4000-8000-000000000004', '[TEST] Zamena izgubljene lične karte', 'Zamena izgubljene lične karte - sa izjavom o gubitku', 'zamena-izgubljene-lk', false, true, false, 'fixed', '1500.00', 'Naknada za izradu', '3-5 radnih dana', 'https://mup.gov.rs', NULL, '2026-06-15T00:00:00Z'),
  ('40000000-0000-4000-8000-000000000005', '[TEST] Pasoš', 'Obnavljanje pasoša', 'pasosh', false, true, false, 'fixed', '3000.00', 'Naknada za izradu', '7-15 radnih dana', 'https://mup.gov.rs', NULL, '2026-06-15T00:00:00Z');

INSERT INTO steps (id, procedure_id, sort_order, title, description) VALUES
  ('50000000-0000-4000-8000-000000000001', '40000000-0000-4000-8000-000000000001', 1, 'Pripremi dokumente', 'Ponesi ličnu kartu i dokaz o pravu na stanovanje na novoj adresi.'),
  ('50000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000001', 2, 'Idi u policijsku stanicu', 'Predaj prijavu prebivališta na šalteru policijske stanice.'),
  ('50000000-0000-4000-8000-000000000003', '40000000-0000-4000-8000-000000000001', 3, 'Preuzmi potvrdu', 'Sačuvaj potvrdu o prijavi, trebaće ti za novu ličnu kartu.'),
  ('50000000-0000-4000-8000-000000000004', '40000000-0000-4000-8000-000000000002', 1, 'Zakaži termin', 'Zakaži termin za izdavanje lične karte.'),
  ('50000000-0000-4000-8000-000000000005', '40000000-0000-4000-8000-000000000002', 2, 'Plati naknadu', 'Uplati naknadu za izradu i ponesi dokaz o uplati.'),
  ('50000000-0000-4000-8000-000000000006', '40000000-0000-4000-8000-000000000002', 3, 'Predaj zahtev', 'Na šalteru predaj zahtev, staru ličnu kartu i dokaz o uplati.'),
  ('50000000-0000-4000-8000-000000000007', '40000000-0000-4000-8000-000000000003', 1, 'Plati naknadu', 'Uplati naknadu za izradu i ponesi dokaz o uplati.'),
  ('50000000-0000-4000-8000-000000000008', '40000000-0000-4000-8000-000000000003', 2, 'Predaj zahtev', 'Na šalteru predaj zahtev i staru ličnu kartu.'),
  ('50000000-0000-4000-8000-000000000009', '40000000-0000-4000-8000-000000000004', 1, 'Prijavi gubitak', 'Na šalteru daj izjavu o gubitku lične karte.'),
  ('50000000-0000-4000-8000-000000000010', '40000000-0000-4000-8000-000000000004', 2, 'Predaj zahtev za novu ličnu kartu', 'Predaj zahtev i dokaz o uplati naknade.'),
  ('50000000-0000-4000-8000-000000000011', '40000000-0000-4000-8000-000000000005', 1, 'Zakaži termin', 'Zakaži termin za predaju zahteva za pasoš.'),
  ('50000000-0000-4000-8000-000000000012', '40000000-0000-4000-8000-000000000005', 2, 'Predaj zahtev', 'Predaj zahtev, ličnu kartu i dokaz o uplati naknade.'),
  ('50000000-0000-4000-8000-000000000013', '40000000-0000-4000-8000-000000000005', 3, 'Preuzmi pasoš', 'Pasoš preuzimaš lično kad stigne obaveštenje.');

INSERT INTO documents (id, procedure_id, name, is_required, note, sort_order) VALUES
  ('60000000-0000-4000-8000-000000000001', '40000000-0000-4000-8000-000000000001', 'Lična karta', true, NULL, 1),
  ('60000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000001', 'Dokaz o pravu na stanovanje', true, 'Ugovor o zakupu ili dokaz o vlasništvu.', 2),
  ('60000000-0000-4000-8000-000000000003', '40000000-0000-4000-8000-000000000002', 'Stara lična karta', true, NULL, 1),
  ('60000000-0000-4000-8000-000000000004', '40000000-0000-4000-8000-000000000002', 'Dokaz o uplati naknade', true, NULL, 2),
  ('60000000-0000-4000-8000-000000000005', '40000000-0000-4000-8000-000000000003', 'Stara lična karta', true, NULL, 1),
  ('60000000-0000-4000-8000-000000000006', '40000000-0000-4000-8000-000000000003', 'Dokaz o uplati naknade', true, NULL, 2),
  ('60000000-0000-4000-8000-000000000007', '40000000-0000-4000-8000-000000000004', 'Izjava o gubitku', true, NULL, 1),
  ('60000000-0000-4000-8000-000000000008', '40000000-0000-4000-8000-000000000004', 'Dokaz o uplati naknade', true, NULL, 2),
  ('60000000-0000-4000-8000-000000000009', '40000000-0000-4000-8000-000000000005', 'Lična karta', true, NULL, 1),
  ('60000000-0000-4000-8000-000000000010', '40000000-0000-4000-8000-000000000005', 'Stari pasoš', false, 'Ako ga imaš.', 2),
  ('60000000-0000-4000-8000-000000000011', '40000000-0000-4000-8000-000000000005', 'Dokaz o uplati naknade', true, NULL, 3);

INSERT INTO procedure_institutions (procedure_id, institution_id, note) VALUES
  ('40000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000001', 'Prijavu podnosiš u policijskoj stanici nadležnoj za novu adresu.'),
  ('40000000-0000-4000-8000-000000000002', '20000000-0000-4000-8000-000000000001', NULL),
  ('40000000-0000-4000-8000-000000000003', '20000000-0000-4000-8000-000000000001', NULL),
  ('40000000-0000-4000-8000-000000000004', '20000000-0000-4000-8000-000000000001', NULL),
  ('40000000-0000-4000-8000-000000000005', '20000000-0000-4000-8000-000000000001', NULL);

INSERT INTO life_events (id, category_id, title, description, icon, slug, sort_order) VALUES
  ('30000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', '[TEST] Istekla mi je lična karta', 'Procedura za obnavljanje istkle lične karte', 'id-card', 'istekla-licna-karta', 1),
  ('30000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000001', '[TEST] Izgubio/la sam ličnu kartu', 'Procedura za zamenu izgubljene lične karte', 'search', 'izgubljena-licna-karta', 2),
  ('30000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000001', '[TEST] Istekao mi je pasoš', 'Procedura za obnavljanje isteklog pasoša', 'plane', 'istekao-pasosh', 3),
  ('30000000-0000-4000-8000-000000000004', '10000000-0000-4000-8000-000000000002', '[TEST] Selim se na novu adresu', 'Sve što trebate da uradite kada se preselite', 'house', 'selim-se-na-novu-adresu', 1),
  ('30000000-0000-4000-8000-000000000010', '10000000-0000-4000-8000-000000000002', '[TEST] Prebacujem prebivalište zbog stana/kuće', 'Promena prebivališta zbog kupovine nekretnine', 'key-round', 'prebacujem-prebivaliste', 4);

INSERT INTO life_event_procedures (life_event_id, procedure_id, sort_order) VALUES
  ('30000000-0000-4000-8000-000000000001', '40000000-0000-4000-8000-000000000003', 1),
  ('30000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000004', 1),
  ('30000000-0000-4000-8000-000000000003', '40000000-0000-4000-8000-000000000005', 1),
  ('30000000-0000-4000-8000-000000000004', '40000000-0000-4000-8000-000000000001', 1),
  ('30000000-0000-4000-8000-000000000004', '40000000-0000-4000-8000-000000000002', 2),
  ('30000000-0000-4000-8000-000000000010', '40000000-0000-4000-8000-000000000001', 1),
  ('30000000-0000-4000-8000-000000000010', '40000000-0000-4000-8000-000000000002', 2);

INSERT INTO procedure_dependencies (life_event_id, procedure_id, depends_on_id) VALUES
  ('30000000-0000-4000-8000-000000000004', '40000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000001'),
  ('30000000-0000-4000-8000-000000000010', '40000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000001');

INSERT INTO synonyms (id, term, maps_to) VALUES
  ('70000000-0000-4000-8000-000000000001', 'putna isprava', 'pasoš'),
  ('70000000-0000-4000-8000-000000000002', 'licna isprava', 'lična karta');

-- Publish: procedures first (they have steps and an institution), then the
-- life events (each now has a published procedure, PR-04).
UPDATE procedures SET status = 'published' WHERE id IN ('40000000-0000-4000-8000-000000000001', '40000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000003', '40000000-0000-4000-8000-000000000004', '40000000-0000-4000-8000-000000000005');
UPDATE life_events SET status = 'published' WHERE id IN ('30000000-0000-4000-8000-000000000001', '30000000-0000-4000-8000-000000000002', '30000000-0000-4000-8000-000000000003', '30000000-0000-4000-8000-000000000004', '30000000-0000-4000-8000-000000000010');
