import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // The service-role client bypasses RLS; only the AI route may use it
  // (ADR 0004, 04 §5.2). A lint error makes a stray import fail CI instead of
  // relying on review.
  {
    files: ["**/*.{ts,tsx,mts}"],
    ignores: ["lib/ai/**", "app/api/v1/ai/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "@/lib/supabase/service-role",
                "**/supabase/service-role",
              ],
              message:
                "The service-role client is reserved for the AI route (ADR 0004).",
            },
          ],
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `supabase gen types`.
    "types/database.ts",
  ]),
]);

export default eslintConfig;
